version: 0.0	
os: linux	
files:	
  - source: /app/
    destination: /home/ubuntu/indoorSensor	
permissions:	
  - object: /	
    pattern: "**"	
    owner: ubuntu	
    group: ubuntu	
hooks:	
  ApplicationStop:	
    - location: scripts/ApplicationStop.sh	
      timeout: 60	
      runas: ubuntu	
  BeforeInstall:	
    - location: scripts/BeforeInstall.sh	
      timeout: 300	
      runas: ubuntu	
  AfterInstall:	
    - location: scripts/AfterInstall.sh	
      timeout: 300	
      runas: ubuntu	
  ApplicationStart:	
    - location: scripts/ApplicationStart.sh	
      timeout: 60	
      runas: ubuntu
